### ISSUE TITLE
An option to publish to GitHub

### ISSUE THREAD

**Issue by slonopotamus** [dawidd6/action-publish-gem#2]
action-publish-gem currently only supports publishing to rubygems.org

It would be nice if publishing to GitHub was also supported.

Relevant docs:

https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-rubygems-for-use-with-github-packages#publishing-a-package

> Publish a package to GitHub Packages, replacing OWNER with the name of the user or organization account that owns the repository containing your project and OCTO-GEM with the name of your gem package.

```
$ gem push --key github \
--host https://rubygems.pkg.github.com/OWNER \
OCTO-GEM-0.0.1.gem
```

**Comment by dawidd6** [comment]
Please feel free to submit a PR adding this feature.

**Comment by dawidd6** [comment]
Implemented here: https://github.com/dawidd6/action-publish-gem/commit/d419b22ebeebe7b2b00b867f8e14937eaedd3c32
